server:
  addr: 127.0.0.1:8080
  http_read_timeout: 30s
  http_write_timeout: 30s
db:
  addr: host=127.0.0.1 port=6432 user=account_svc password=account_svc dbname=account_svc sslmode=disable
  max_idle_conns: 10
  max_open_conns: 10
debit_limit: 10